### ISSUE TITLE
Add transmission support

### ISSUE THREAD

**Issue by matthew-reynolds** [uwreact/frc_control#1]
# 📚 Meta Issue

Support [transmissions](http://wiki.ros.org/ros_control#Transmissions). This is most critical for mechanisms such as the drive train, where teams often have a 6 wheel skid-steer drive powered by 2 or 4 motors. For example, many teams would require a 2in-3out transmission (ideally with configurable reduction, allowing for multi-speed gearboxes)  for their drive bases.

## Tracking:
 - [ ] Integrate transmissions into `FRCRobotHW` #2
 - [ ] Finalize and document expected transmission syntax in YAML and URDF #3
 - [ ] Create custom X in, Y out transmissions #4 
 - [ ] Support 2-speed transmissions #5

In order to maintain feature parity with simulation, this must also be implemented in Gazebo.
