### ISSUE TITLE
Create QT-based driver station

### ISSUE THREAD

**Issue by matthew-reynolds** [uwreact/frc_control#13]
# 📚 Meta Issue

We require a driver station for 2 purposes; First, it will be required for running the robot in simulation, since the official NI driver station is only for real robots. Additionally, since code will be developed in Ubuntu, it would be nice to have the ability to drive real robots from Ubuntu as well. Since the NI driver station is Windows only, we need our own.

Note here that [QDriverStation](https://github.com/FRC-Utilities/QDriverStation) is no longer supported, which is a shame since it would have been trivial to add a ROS wrapper around. We may pick up support of this one day, but for the time being it's not required.

This driver station should be build using [rqt](http://wiki.ros.org/rqt), and will just publish joystick and game data for the rest of the system, mimicking the behaviour of the real robot.

## Tracking

 - [x] #48 Create skeleton QT app with blank window
 - [x] #49 Create QT app layout as a `.ui` file, mimicking the real driver station as closely as possible
 - [x] #50 Publish enabled/disabled, teleop/auto, match time, etc
 - [ ] #51 Read from USB joysticks and publish their data
 - [x] #53 Subscribe to robot status messages, display data
 - [ ] #52 Subscribe to joystick feedback, apply rumble to the USB joysticks

**Comment by matthew-reynolds** [comment]
Updated to metaissue
