### ISSUE TITLE
Add static analysis, code formatting

### ISSUE THREAD

**Issue by matthew-reynolds** [uwreact/frc_control#40]
# 📚 Meta Issue

We want to have consistent code. The best ways to do this is with static analysis and code formatting tools.

For C++, we will use clang-format and clang-tidy for style and analysis respectively.
For python, we will use yapf and pylint for style and analysis respectively.
For catkin files, we will use catkin_lint.
**TODO** Markdown linting??

## Tracking

 - [x] #33 Add clang-format configuration file
 - [x] #36 Add yapf configuration file
 - [x] #37 Add clang-tidy configuration file
 - [x] #39 Add pylint configuration file
 - [x] #38 Add clang-format, clang-tidy, yapf, pylint, and catkin_lint to CI

**Comment by matthew-reynolds** [comment]
All subtasks completed, closing meta-issue.

Note that Markdown, Bash, CMakeLists, and XML linting are all unimportant at this time. Perhaps we may implement them later, but they are not currently a goal, so this issue is free to be closed.
