### ISSUE TITLE
Simplify installation

### ISSUE THREAD

**Issue by matthew-reynolds** [uwreact/frc_control#7]
# 📚 Meta Issue

Building and installing this package is unlike most ROS packages due to the requirement to cross-compile for the roboRIO. For FRC teams, it is also completely different from the standard roboRIO setup procedure. As such, we need to create tools and scripts to help teams setup their development environment and deploy their code to the RIO. We also need to *very* thoroughly document everything, and provide a clear tutorial.

## Tracking

 - [x] Create script to setup development workspace, including ROS cross-compilation #8
 - [x] Create script to install ROS on the roboRIO #9
 - [x] Create script to deploy code to the RIO #10
 - [x] *Thoroughly* document environment setup procedure #11
 - [x] Document RIO setup and code deploy #30

**Comment by matthew-reynolds** [comment]
#11 was split into #30. Updating meta issue to track #30 as well

**Comment by matthew-reynolds** [comment]
#9, #10, and #30 closed in #64.

All subtasks complete.
